### ISSUE TITLE
【依頼】ヘルプを追加してもらいたいプラグインがある

### ISSUE THREAD

**Issue by lambdalisue** [osyo-manga/vimhelp-jp#3]
開発時に使えると捗るので以下のものを追加して頂けると助かります。

- [lambdalisue/vital-VCS-Git](https://github.com/lambdalisue/vital-VCS-Git)
- [lambdalisue/vital-ArgumentParser](https://github.com/lambdalisue/vital-ArgumentParser)
- [osyo-manga/vital-over](https://github.com/osyo-manga/vital-over)

気が向いた時にでもご判断お願いいたします。

**Comment by osyo-manga** [comment]
週末にでも追加しておきまする。
（最近放置グセがあるので反応がなければ ping ください…。

**Comment by osyo-manga** [comment]
追加しました
http://vim-help-jp.herokuapp.com/#Vital.Over.Commandline-keymapping

**Comment by lambdalisue** [comment]
ありがとうございました！

**Comment by osyo-manga** [comment]
ちなみに関係無いですが vimhelp は heroku の無料枠で動いてるので突然死にます（小声
